// TEMPORARY DATA

export let role = "admin";
export const teachersData = [
  {
    id: 1,
    teacherId: "۰۰۱۲۳۴۵۶۷۸",
    name: "علی رضایی",
    email: "ali.rezaei@example.com",
    photo: "/teacher1.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۱",
    subjects: ["ریاضی", "هندسه"],
    classes: ["۱ ب", "۲ الف", "۳ ج"],
    address: "خیابان انقلاب، پلاک ۱۲، تهران"
  },
  {
    id: 2,
    teacherId: "۰۰۲۳۴۵۶۷۸۹",
    name: "فاطمه محمدی",
    email: "fatemeh.mohammadi@example.com",
    photo: "/teacher2.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۲",
    subjects: ["فیزیک", "شیمی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "بلوار کشاورز، پلاک ۲۵، تهران"
  },
  {
    id: 3,
    teacherId: "۰۰۳۴۵۶۷۸۹۰",
    name: "حسین کریمی",
    email: "hossein.karimi@example.com",
    photo: "/teacher3.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۳",
    subjects: ["زیست‌شناسی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "میدان آزادی، پلاک ۸، تهران"
  },
  {
    id: 4,
    teacherId: "۰۰۴۵۶۷۸۹۰۱",
    name: "زهرا نجفی",
    email: "zahra.najafi@example.com",
    photo: "/teacher4.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۴",
    subjects: ["تاریخ"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان ولیعصر، پلاک ۳۰، تهران"
  },
  {
    id: 5,
    teacherId: "۰۰۵۶۷۸۹۰۱۲",
    name: "محمد حسینی",
    email: "mohammad.hosseini@example.com",
    photo: "/teacher5.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۵",
    subjects: ["موسیقی", "تاریخ"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان جمهوری، پلاک ۱۵، تهران"
  },
  {
    id: 6,
    teacherId: "۰۰۶۷۸۹۰۱۲۳",
    name: "نرگس احمدی",
    email: "narges.ahmadi@example.com",
    photo: "/teacher6.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۶",
    subjects: ["فیزیک"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "بلوار نلسون ماندلا، پلاک ۱۰، تهران"
  },
  {
    id: 7,
    teacherId: "۰۰۷۸۹۰۱۲۳۴",
    name: "رضا موسوی",
    email: "reza.mousavi@example.com",
    photo: "/teacher7.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۷",
    subjects: ["زبان انگلیسی", "زبان عربی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان شهید بهشتی، پلاک ۲۲، تهران"
  },
  {
    id: 8,
    teacherId: "۰۰۸۹۰۱۲۳۴۵",
    name: "مریم جعفری",
    email: "maryam.jafari@example.com",
    photo: "/teacher8.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۸",
    subjects: ["ریاضی", "هندسه"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان کارگر شمالی، پلاک ۴۰، تهران"
  },
  {
    id: 9,
    teacherId: "۰۰۹۰۱۲۳۴۵۶",
    name: "امیرحسین غفاری",
    email: "amirhossein.ghafari@example.com",
    photo: "/teacher9.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۹",
    subjects: ["ادبیات فارسی", "زبان انگلیسی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان پیروزی، پلاک ۱۸، تهران"
  },
  {
    id: 10,
    teacherId: "۰۱۰۱۲۳۴۵۶۷",
    name: "سارا تقوی",
    email: "sara.taghavi@example.com",
    photo: "/teacher10.png",
    phone: "۰۹۱۲۳۴۵۶۷۹۰",
    subjects: ["زیست‌شناسی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان دماوند، پلاک ۵۰، تهران"
  }
];



export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const parentsData = [
  {
    id: 1,
    name: "علی احمدی",
    students: ["سارا احمدی"],
    email: "ali.ahmadi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۱",
    address: "خیابان انقلاب، پلاک ۱۲، تهران",
  },
  {
    id: 2,
    name: "فاطمه محمدی",
    students: ["نرگس محمدی"],
    email: "fatemeh.mohammadi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۲",
    address: "بلوار کشاورز، پلاک ۲۵، تهران",
  },
  {
    id: 3,
    name: "حسین رضایی",
    students: ["یاسمن رضایی"],
    email: "hossein.rezaei@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۳",
    address: "میدان آزادی، پلاک ۸، تهران",
  },
  {
    id: 4,
    name: "محمد جعفری",
    students: ["پرستو جعفری", "پارسا جعفری"],
    email: "mohammad.jafari@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۴",
    address: "خیابان ولیعصر، پلاک ۳۰، تهران",
  },
  {
    id: 5,
    name: "زهرا کریمی",
    students: ["ترانه کریمی"],
    email: "zahra.karimi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۵",
    address: "خیابان جمهوری، پلاک ۱۵، تهران",
  },
  {
    id: 6,
    name: "مهدی موسوی",
    students: ["آرش موسوی"],
    email: "mehdi.mousavi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۶",
    address: "بلوار نلسون ماندلا، پلاک ۱۰، تهران",
  },
  {
    id: 7,
    name: "نازنین تقوی",
    students: ["ستاره تقوی", "آرین تقوی"],
    email: "nazanin.taghavi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۷",
    address: "خیابان شهید بهشتی، پلاک ۲۲، تهران",
  },
  {
    id: 8,
    name: "رضا حسینی",
    students: ["کاوه حسینی"],
    email: "reza.hosseini@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۸",
    address: "خیابان کارگر شمالی، پلاک ۴۰، تهران",
  },
  {
    id: 9,
    name: "لیلا غفاری",
    students: ["دانیال غفاری", "آوا غفاری"],
    email: "leila.ghafari@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۹",
    address: "خیابان پیروزی، پلاک ۱۸، تهران",
  },
  {
    id: 10,
    name: "امیرحسین نجفی",
    students: ["نیما نجفی"],
    email: "amirhossein.najafi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۹۰",
    address: "خیابان دماوند، پلاک ۵۰، تهران",
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];
export const studentsData = [
  {
    id: 1,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "علی رضایی",
    email: "ali@rezai.com",
    photo: "/student1.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۱ ب",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 2,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "سارا احمدی",
    email: "sara@ahmadi.com",
    photo: "/student2.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 3,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "محمد موسوی",
    email: "mohammad@mosavi.com",
    photo: "/student3.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 4,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "زهرا کاظمی",
    email: "zahra@kazemi.com",
    photo: "/student4.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 5,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "رضا صادقی",
    email: "reza@sadeghi.com",
    photo: "/student5.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 6,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "مریم شریفی",
    email: "maryam@sharifi.com",
    photo: "/student6.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 7,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "حسین کریمی",
    email: "hossein@karimi.com",
    photo: "/student7.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 8,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "ندا رستمی",
    email: "neda@rostami.com",
    photo: "/student8.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 9,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "امیر نادری",
    email: "amir@naderi.com",
    photo: "/student9.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 10,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "لیلا جعفری",
    email: "leila@jafari.com",
    photo: "/student10.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
];



export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: true,
    start: new Date(2025, 6, 31, 8, 0), // امروز
    end: new Date(2025, 6, 31, 8, 45),
    className: "today-event", // کلاس برای امروز
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 12, 9, 0), // روز دیگر
    end: new Date(2025, 6, 12, 9, 45),
    className: "other-day-event", // کلاس برای روز دیگر
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 12, 10, 0),
    end: new Date(2025, 6, 12, 10, 45),
    className: "other-day-event",
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 12, 11, 0),
    end: new Date(2025, 6, 12, 11, 45),
    className: "other-day-event",
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 12, 13, 0),
    end: new Date(2025, 6, 12, 13, 45),
    className: "other-day-event",
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 12, 10, 0),
    end: new Date(2025, 6, 12, 10, 45),
    className: "other-day-event",
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 13, 9, 0),
    end: new Date(2025, 6, 13, 9, 45),
    className: "other-day-event",
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 13, 10, 0),
    end: new Date(2025, 6, 13, 10, 45),
    className: "other-day-event",
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 13, 11, 0),
    end: new Date(2025, 6, 13, 11, 45),
    className: "other-day-event",
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 13, 14, 0),
    end: new Date(2025, 6, 13, 14, 45),
    className: "other-day-event",
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 14, 8, 0),
    end: new Date(2025, 6, 14, 8, 45),
    className: "other-day-event",
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 14, 10, 0),
    end: new Date(2025, 6, 14, 10, 45),
    className: "other-day-event",
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 14, 13, 0),
    end: new Date(2025, 6, 14, 13, 45),
    className: "other-day-event",
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 14, 14, 0),
    end: new Date(2025, 6, 14, 14, 45),
    className: "other-day-event",
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 15, 9, 0),
    end: new Date(2025, 6, 15, 9, 45),
    className: "other-day-event",
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 15, 10, 0),
    end: new Date(2025, 6, 15, 10, 45),
    className: "other-day-event",
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 15, 11, 0),
    end: new Date(2025, 6, 15, 11, 45),
    className: "other-day-event",
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 15, 14, 0),
    end: new Date(2025, 6, 15, 14, 45),
    className: "other-day-event",
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 16, 8, 0),
    end: new Date(2025, 6, 16, 8, 45),
    className: "other-day-event",
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 16, 9, 0),
    end: new Date(2025, 6, 16, 9, 45),
    className: "other-day-event",
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 16, 11, 0),
    end: new Date(2025, 6, 16, 11, 45),
    className: "other-day-event",
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 16, 13, 0),
    end: new Date(2025, 6, 16, 13, 45),
    className: "other-day-event",
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 16, 14, 0),
    end: new Date(2025, 6, 16, 14, 45),
    className: "other-day-event",
  },
  // اضافه کردن رویدادهای جدید
  {
    title: "Geography",
    allDay: false,
    start: new Date(2025, 7, 1, 10, 0), // امروز
    end: new Date(2025, 7, 1, 11, 0),
    className: "today-event", // کلاس برای امروز
  },
  {
    title: "Art",
    allDay: false,
    start: new Date(2025, 6, 29, 10, 0), // روز دیگر
    end: new Date(2025, 6, 29, 11, 0),
    className: "other-day-event", // کلاس برای روز دیگر
  },
  {
    title: "Music",
    allDay: false,
    start: new Date(2025, 7, 1, 8, 0), // روز دیگر
    end: new Date(2025, 7, 1, 9, 0),
    className: "other-day-event", // کلاس برای روز دیگر
  },
];