// TEMPORARY DATA

export let role = "admin";
export const teachersData = [
  {
    id: 1,
    teacherId: "۰۰۱۲۳۴۵۶۷۸",
    name: "علی رضایی",
    email: "ali.rezaei@example.com",
    photo: "/teacher1.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۱",
    subjects: ["ریاضی", "هندسه"],
    classes: ["۱ ب", "۲ الف", "۳ ج"],
    address: "خیابان انقلاب، پلاک ۱۲، تهران"
  },
  {
    id: 2,
    teacherId: "۰۰۲۳۴۵۶۷۸۹",
    name: "فاطمه محمدی",
    email: "fatemeh.mohammadi@example.com",
    photo: "/teacher2.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۲",
    subjects: ["فیزیک", "شیمی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "بلوار کشاورز، پلاک ۲۵، تهران"
  },
  {
    id: 3,
    teacherId: "۰۰۳۴۵۶۷۸۹۰",
    name: "حسین کریمی",
    email: "hossein.karimi@example.com",
    photo: "/teacher3.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۳",
    subjects: ["زیست‌شناسی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "میدان آزادی، پلاک ۸، تهران"
  },
  {
    id: 4,
    teacherId: "۰۰۴۵۶۷۸۹۰۱",
    name: "زهرا نجفی",
    email: "zahra.najafi@example.com",
    photo: "/teacher4.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۴",
    subjects: ["تاریخ"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان ولیعصر، پلاک ۳۰، تهران"
  },
  {
    id: 5,
    teacherId: "۰۰۵۶۷۸۹۰۱۲",
    name: "محمد حسینی",
    email: "mohammad.hosseini@example.com",
    photo: "/teacher5.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۵",
    subjects: ["موسیقی", "تاریخ"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان جمهوری، پلاک ۱۵، تهران"
  },
  {
    id: 6,
    teacherId: "۰۰۶۷۸۹۰۱۲۳",
    name: "نرگس احمدی",
    email: "narges.ahmadi@example.com",
    photo: "/teacher6.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۶",
    subjects: ["فیزیک"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "بلوار نلسون ماندلا، پلاک ۱۰، تهران"
  },
  {
    id: 7,
    teacherId: "۰۰۷۸۹۰۱۲۳۴",
    name: "رضا موسوی",
    email: "reza.mousavi@example.com",
    photo: "/teacher7.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۷",
    subjects: ["زبان انگلیسی", "زبان عربی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان شهید بهشتی، پلاک ۲۲، تهران"
  },
  {
    id: 8,
    teacherId: "۰۰۸۹۰۱۲۳۴۵",
    name: "مریم جعفری",
    email: "maryam.jafari@example.com",
    photo: "/teacher8.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۸",
    subjects: ["ریاضی", "هندسه"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان کارگر شمالی، پلاک ۴۰، تهران"
  },
  {
    id: 9,
    teacherId: "۰۰۹۰۱۲۳۴۵۶",
    name: "امیرحسین غفاری",
    email: "amirhossein.ghafari@example.com",
    photo: "/teacher9.png",
    phone: "۰۹۱۲۳۴۵۶۷۸۹",
    subjects: ["ادبیات فارسی", "زبان انگلیسی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان پیروزی، پلاک ۱۸، تهران"
  },
  {
    id: 10,
    teacherId: "۰۱۰۱۲۳۴۵۶۷",
    name: "سارا تقوی",
    email: "sara.taghavi@example.com",
    photo: "/teacher10.png",
    phone: "۰۹۱۲۳۴۵۶۷۹۰",
    subjects: ["زیست‌شناسی"],
    classes: ["۵ الف", "۴ ب", "۳ ج"],
    address: "خیابان دماوند، پلاک ۵۰، تهران"
  }
];



export const subjectsData = [
  {
    id: 1,
    name: "ریاضی",
    teachers: ["علی رضایی", "سمیه قاسمی"],
  },
  {
    id: 2,
    name: "انگلیسی",
    teachers: ["مهدی نادری", "فاطمه حسینی"],
  },
  {
    id: 3,
    name: "فیزیک",
    teachers: ["حسین اکبری", "زینب احمدی"],
  },
  {
    id: 4,
    name: "شیمی",
    teachers: ["نیما سلیمانی", "سارا محمدی"],
  },
  {
    id: 5,
    name: "زیست‌شناسی",
    teachers: ["علی رحمانی", "کیمیا رستمی"],
  },
  {
    id: 6,
    name: "تاریخ",
    teachers: ["احمد حسینی", "مینا کرمی"],
  },
  {
    id: 7,
    name: "جغرافیا",
    teachers: ["فاطمه قاسمی", "رضا قاسمی"],
  },
  {
    id: 8,
    name: "هنر",
    teachers: ["زهره سلیمانی", "نیلوفر احمدی"],
  },
  {
    id: 9,
    name: "موسیقی",
    teachers: ["علی نادری", "مریم سادات"],
  },
  {
    id: 10,
    name: "ادبیات",
    teachers: ["فرزاد رضایی", "سمیه علیزاده"],
  },
];
export const parentsData = [
  {
    id: 1,
    name: "علی احمدی",
    students: ["سارا احمدی"],
    email: "ali.ahmadi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۱",
    address: "خیابان انقلاب، پلاک ۱۲، تهران",
  },
  {
    id: 2,
    name: "فاطمه محمدی",
    students: ["نرگس محمدی"],
    email: "fatemeh.mohammadi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۲",
    address: "بلوار کشاورز، پلاک ۲۵، تهران",
  },
  {
    id: 3,
    name: "حسین رضایی",
    students: ["یاسمن رضایی"],
    email: "hossein.rezaei@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۳",
    address: "میدان آزادی، پلاک ۸، تهران",
  },
  {
    id: 4,
    name: "محمد جعفری",
    students: ["پرستو جعفری", "پارسا جعفری"],
    email: "mohammad.jafari@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۴",
    address: "خیابان ولیعصر، پلاک ۳۰، تهران",
  },
  {
    id: 5,
    name: "زهرا کریمی",
    students: ["ترانه کریمی"],
    email: "zahra.karimi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۵",
    address: "خیابان جمهوری، پلاک ۱۵، تهران",
  },
  {
    id: 6,
    name: "مهدی موسوی",
    students: ["آرش موسوی"],
    email: "mehdi.mousavi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۶",
    address: "بلوار نلسون ماندلا، پلاک ۱۰، تهران",
  },
  {
    id: 7,
    name: "نازنین تقوی",
    students: ["ستاره تقوی", "آرین تقوی"],
    email: "nazanin.taghavi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۷",
    address: "خیابان شهید بهشتی، پلاک ۲۲، تهران",
  },
  {
    id: 8,
    name: "رضا حسینی",
    students: ["کاوه حسینی"],
    email: "reza.hosseini@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۸",
    address: "خیابان کارگر شمالی، پلاک ۴۰، تهران",
  },
  {
    id: 9,
    name: "لیلا غفاری",
    students: ["دانیال غفاری", "آوا غفاری"],
    email: "leila.ghafari@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۸۹",
    address: "خیابان پیروزی، پلاک ۱۸، تهران",
  },
  {
    id: 10,
    name: "امیرحسین نجفی",
    students: ["نیما نجفی"],
    email: "amirhossein.najafi@example.com",
    phone: "۰۹۱۲۳۴۵۶۷۹۰",
    address: "خیابان دماوند، پلاک ۵۰، تهران",
  },
];
export const classesData = [
  {
    id: 1,
    name: "هفتم ۱",
    capacity: 20,
    grade: 7,
    supervisor: "علی رحمانی",
  },
  {
    id: 2,
    name: "هفتم ۲",
    capacity: 22,
    grade: 7,
    supervisor: "سارا محمدی",
  },
  {
    id: 3,
    name: "هشتم ۱",
    capacity: 20,
    grade: 8,
    supervisor: "حسین اکبری",
  },
  {
    id: 4,
    name: "هشتم ۲",
    capacity: 18,
    grade: 8,
    supervisor: "مهدی حسینی",
  },
  {
    id: 5,
    name: "نهم ۱",
    capacity: 16,
    grade: 9,
    supervisor: "فاطمه قاسمی",
  },
  {
    id: 6,
    name: "نهم ۲",
    capacity: 20,
    grade: 9,
    supervisor: "نیما سلیمانی",
  },
  {
    id: 7,
    name: "نهم ۳",
    capacity: 18,
    grade: 9,
    supervisor: "کیمیا رستمی",
  },
  {
    id: 8,
    name: "هفتم ۳",
    capacity: 22,
    grade: 7,
    supervisor: "احمد حسینی",
  },
  {
    id: 9,
    name: "هشتم ۳",
    capacity: 18,
    grade: 8,
    supervisor: "محمد نادری",
  },
  {
    id: 10,
    name: "هشتم ۴",
    capacity: 20,
    grade: 8,
    supervisor: "زینب احمدی",
  },
];
export const studentsData = [
  {
    id: 1,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "علی رضایی",
    email: "ali@rezai.com",
    photo: "/student1.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۱ ب",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 2,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "سارا احمدی",
    email: "sara@ahmadi.com",
    photo: "/student2.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 3,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "محمد موسوی",
    email: "mohammad@mosavi.com",
    photo: "/student3.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 4,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "زهرا کاظمی",
    email: "zahra@kazemi.com",
    photo: "/student4.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 5,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "رضا صادقی",
    email: "reza@sadeghi.com",
    photo: "/student5.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 6,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "مریم شریفی",
    email: "maryam@sharifi.com",
    photo: "/student6.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 7,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "حسین کریمی",
    email: "hossein@karimi.com",
    photo: "/student7.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 8,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "ندا رستمی",
    email: "neda@rostami.com",
    photo: "/student8.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 9,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "امیر نادری",
    email: "amir@naderi.com",
    photo: "/student9.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
  {
    id: 10,
    studentId: "۱۲۳۴۵۶۷۸۹۰",
    name: "لیلا جعفری",
    email: "leila@jafari.com",
    photo: "/student10.png",
    phone: "۱۲۳۴۵۶۷۸۹۰",
    grade: 5,
    class: "۵ الف",
    address: "خیابان اصلی ۱۲۳، تهران، ایران",
  },
];


export const lessonsData = [
  {
    id: 1,
    subject: "ریاضی",
    class: "هفتم ۱",
    teacher: "احمد حسینی",
  },
  {
    id: 2,
    subject: "انگلیسی",
    class: "هشتم ۱",
    teacher: "مریم سادات",
  },
  {
    id: 3,
    subject: "علوم",
    class: "نهم ۱",
    teacher: "حسین اکبری",
  },
  {
    id: 4,
    subject: "مطالعات اجتماعی",
    class: "هفتم ۲",
    teacher: "علی رحیمی",
  },
  {
    id: 5,
    subject: "هنر",
    class: "هشتم ۲",
    teacher: "سارا محمدی",
  },
  {
    id: 6,
    subject: "موسیقی",
    class: "نهم ۲",
    teacher: "کیمیا رستمی",
  },
  {
    id: 7,
    subject: "تاریخ",
    class: "هفتم ۱",
    teacher: "رضا قاسمی",
  },
  {
    id: 8,
    subject: "جغرافیا",
    class: "هشتم ۱",
    teacher: "فاطمه نوری",
  },
  {
    id: 9,
    subject: "فیزیک",
    class: "نهم ۲",
    teacher: "سعید احمدی",
  },
  {
    id: 10,
    subject: "شیمی",
    class: "هشتم ۲",
    teacher: "سمیه علیزاده",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "ریاضی",
    class: "هفتم ۱",
    teacher: "مینا کرمی",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 2,
    subject: "انگلیسی",
    class: "هشتم ۱",
    teacher: "رضا نادری",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 3,
    subject: "علوم",
    class: "نهم ۱",
    teacher: "مهدی حسینی",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 4,
    subject: "مطالعات اجتماعی",
    class: "هفتم ۲",
    teacher: "علی اکبری",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 5,
    subject: "هنر",
    class: "هشتم ۲",
    teacher: "نیما سلیمانی",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 6,
    subject: "موسیقی",
    class: "نهم ۱",
    teacher: "فاطمه قاسمی",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 7,
    subject: "تاریخ",
    class: "هفتم ۱",
    teacher: "علی نوری",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 8,
    subject: "جغرافیا",
    class: "هشتم ۱",
    teacher: "سارا احمدی",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 9,
    subject: "فیزیک",
    class: "نهم ۱",
    teacher: "حمید حسینی",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 10,
    subject: "شیمی",
    class: "هشتم ۱",
    teacher: "سمیه صادقی",
    date: "۱۴۰۵-۰۱-۰۱",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "ریاضی",
    class: "هفتم",
    teacher: "احمد حسینی",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 2,
    subject: "انگلیسی",
    class: "هشتم",
    teacher: "مریم سادات",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 3,
    subject: "علوم",
    class: "نهم",
    teacher: "حسین اکبری",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 4,
    subject: "مطالعات اجتماعی",
    class: "هفتم",
    teacher: "علی رحیمی",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 5,
    subject: "هنر",
    class: "هشتم",
    teacher: "سارا محمدی",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 6,
    subject: "موسیقی",
    class: "نهم",
    teacher: "کیمیا رستمی",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 7,
    subject: "تاریخ",
    class: "هفتم",
    teacher: "رضا قاسمی",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 8,
    subject: "جغرافیا",
    class: "هشتم",
    teacher: "فاطمه نوری",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 9,
    subject: "فیزیک",
    class: "نهم",
    teacher: "سعید احمدی",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 10,
    subject: "شیمی",
    class: "هشتم",
    teacher: "سمیه علیزاده",
    dueDate: "۱۴۰۵-۰۱-۰۱",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "ریاضی",
    class: "نهم",
    teacher: "علی رضایی",
    student: "حمید نوری",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 18, // نمره از ۲۰
  },
  {
    id: 2,
    subject: "انگلیسی",
    class: "هشتم",
    teacher: "علی رضایی",
    student: "سارا محمدی",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 19,
  },
  {
    id: 3,
    subject: "علوم",
    class: "هفتم",
    teacher: "علی رضایی",
    student: "مهدی حسینی",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 17,
  },
  {
    id: 4,
    subject: "مطالعات اجتماعی",
    class: "نهم",
    teacher: "علی رضایی",
    student: "زینب احمدی",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 16,
  },
  {
    id: 5,
    subject: "هنر",
    class: "هشتم",
    teacher: "علی رضایی",
    student: "نیما اکبری",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 20,
  },
  {
    id: 6,
    subject: "موسیقی",
    class: "هفتم",
    teacher: "علی رضایی",
    student: "فاطمه صادقی",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 15,
  },
  {
    id: 7,
    subject: "تاریخ",
    class: "نهم",
    teacher: "علی رضایی",
    student: "امیررضا کریمی",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 19,
  },
  {
    id: 8,
    subject: "جغرافیا",
    class: "هشتم",
    teacher: "علی رضایی",
    student: "مینا سلیمانی",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 18,
  },
  {
    id: 9,
    subject: "فیزیک",
    class: "نهم",
    teacher: "علی رضایی",
    student: "علی اکبر نژاد",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 20,
  },
  {
    id: 10,
    subject: "شیمی",
    class: "هشتم",
    teacher: "علی رضایی",
    student: "سمیه قاسمی",
    date: "۱۴۰۵-۰۱-۰۱",
    type: "آزمون",
    score: 17,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "سفر به دریاچه",
    class: "۱ الف",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 2,
    title: "پیک نیک",
    class: "۲ الف",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 3,
    title: "سفر به ساحل",
    class: "۳ الف",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 4,
    title: "سفر به موزه",
    class: "۴ الف",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 5,
    title: "کنسرت موسیقی",
    class: "۵ الف",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 6,
    title: "نمایش شعبده بازی",
    class: "۱ ب",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 7,
    title: "سفر به دریاچه",
    class: "۲ ب",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 8,
    title: "مسابقه دوچرخه سواری",
    class: "۳ ب",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 9,
    title: "نمایشگاه هنری",
    class: "۴ ب",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
  {
    id: 10,
    title: "مسابقات ورزشی",
    class: "۵ ب",
    date: "۱۴۰۵-۰۱-۰۱",
    startTime: "۱۰:۰۰",
    endTime: "۱۱:۰۰",
  },
];
export const announcementsData = [
  {
    id: 1,
    title: "درباره آزمون ریاضی هفتم ۴",
    class: "۴ هفتم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 2,
    title: "درباره آزمون ریاضی هفتم ۳",
    class: "۳ هفتم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 3,
    title: "درباره آزمون ریاضی هشتم ۳",
    class: "۳ هشتم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 4,
    title: "درباره آزمون ریاضی هفتم ۶",
    class: "۶ هفتم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 5,
    title: "درباره آزمون ریاضی نهم ۸",
    class: "۸ نهم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 6,
    title: "درباره آزمون ریاضی هفتم ۲",
    class: "۲ هفتم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 7,
    title: "درباره آزمون ریاضی هشتم ۴",
    class: "۴ هشتم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 8,
    title: "درباره آزمون ریاضی نهم ۴",
    class: "۴ نهم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 9,
    title: "درباره آزمون ریاضی نهم ۳",
    class: "۳ نهم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
  {
    id: 10,
    title: "درباره آزمون ریاضی نهم ۱",
    class: "۱ نهم",
    date: "۱۴۰۵-۰۱-۰۱",
  },
];

// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "ریاضی",
    allDay: true,
    start: new Date(2025, 6, 31, 8, 0), // امروز
    end: new Date(2025, 6, 31, 8, 45),
    className: "today-event", // کلاس برای امروز
  },
  {
    title: "زبان انگلیسی",
    allDay: false,
    start: new Date(2025, 6, 12, 9, 0), // روز دیگر
    end: new Date(2025, 6, 12, 9, 45),
    className: "other-day-event", // کلاس برای روز دیگر
  },
  {
    title: "زیست‌شناسی",
    allDay: false,
    start: new Date(2025, 6, 12, 10, 0),
    end: new Date(2025, 6, 12, 10, 45),
    className: "other-day-event",
  },
  {
    title: "فیزیک",
    allDay: false,
    start: new Date(2025, 6, 12, 11, 0),
    end: new Date(2025, 6, 12, 11, 45),
    className: "other-day-event",
  },
  {
    title: "شیمی",
    allDay: false,
    start: new Date(2025, 6, 12, 13, 0),
    end: new Date(2025, 6, 12, 13, 45),
    className: "other-day-event",
  },
  {
    title: "تاریخ",
    allDay: false,
    start: new Date(2025, 6, 12, 10, 0),
    end: new Date(2025, 6, 12, 10, 45),
    className: "other-day-event",
  },
  {
    title: "زبان انگلیسی",
    allDay: false,
    start: new Date(2025, 6, 13, 9, 0),
    end: new Date(2025, 6, 13, 9, 45),
    className: "other-day-event",
  },
  {
    title: "زیست‌شناسی",
    allDay: false,
    start: new Date(2025, 6, 13, 10, 0),
    end: new Date(2025, 6, 13, 10, 45),
    className: "other-day-event",
  },
  {
    title: "فیزیک",
    allDay: false,
    start: new Date(2025, 6, 13, 11, 0),
    end: new Date(2025, 6, 13, 11, 45),
    className: "other-day-event",
  },
  {
    title: "تاریخ",
    allDay: false,
    start: new Date(2025, 6, 13, 14, 0),
    end: new Date(2025, 6, 13, 14, 45),
    className: "other-day-event",
  },
  {
    title: "ریاضی",
    allDay: false,
    start: new Date(2025, 6, 14, 8, 0),
    end: new Date(2025, 6, 14, 8, 45),
    className: "other-day-event",
  },
  {
    title: "زیست‌شناسی",
    allDay: false,
    start: new Date(2025, 6, 14, 10, 0),
    end: new Date(2025, 6, 14, 10, 45),
    className: "other-day-event",
  },
  {
    title: "شیمی",
    allDay: false,
    start: new Date(2025, 6, 14, 13, 0),
    end: new Date(2025, 6, 14, 13, 45),
    className: "other-day-event",
  },
  {
    title: "تاریخ",
    allDay: false,
    start: new Date(2025, 6, 14, 14, 0),
    end: new Date(2025, 6, 14, 14, 45),
    className: "other-day-event",
  },
  {
    title: "زبان انگلیسی",
    allDay: false,
    start: new Date(2025, 6, 15, 9, 0),
    end: new Date(2025, 6, 15, 9, 45),
    className: "other-day-event",
  },
  {
    title: "زیست‌شناسی",
    allDay: false,
    start: new Date(2025, 6, 15, 10, 0),
    end: new Date(2025, 6, 15, 10, 45),
    className: "other-day-event",
  },
  {
    title: "فیزیک",
    allDay: false,
    start: new Date(2025, 6, 15, 11, 0),
    end: new Date(2025, 6, 15, 11, 45),
    className: "other-day-event",
  },
  {
    title: "تاریخ",
    allDay: false,
    start: new Date(2025, 6, 15, 14, 0),
    end: new Date(2025, 6, 15, 14, 45),
    className: "other-day-event",
  },
  {
    title: "ریاضی",
    allDay: false,
    start: new Date(2025, 6, 16, 8, 0),
    end: new Date(2025, 6, 16, 8, 45),
    className: "other-day-event",
  },
  {
    title: "زبان انگلیسی",
    allDay: false,
    start: new Date(2025, 6, 16, 9, 0),
    end: new Date(2025, 6, 16, 9, 45),
    className: "other-day-event",
  },
  {
    title: "فیزیک",
    allDay: false,
    start: new Date(2025, 6, 16, 11, 0),
    end: new Date(2025, 6, 16, 11, 45),
    className: "other-day-event",
  },
  {
    title: "شیمی",
    allDay: false,
    start: new Date(2025, 6, 16, 13, 0),
    end: new Date(2025, 6, 16, 13, 45),
    className: "other-day-event",
  },
  {
    title: "تاریخ",
    allDay: false,
    start: new Date(2025, 6, 16, 14, 0),
    end: new Date(2025, 6, 16, 14, 45),
    className: "other-day-event",
  },
  // اضافه کردن رویدادهای جدید
  {
    title: "جغرافیا",
    allDay: false,
    start: new Date(2025, 7, 1, 10, 0), // امروز
    end: new Date(2025, 7, 1, 11, 0),
    className: "today-event", // کلاس برای امروز
  },
  {
    title: "هنر",
    allDay: false,
    start: new Date(2025, 6, 29, 10, 0), // روز دیگر
    end: new Date(2025, 6, 29, 11, 0),
    className: "other-day-event", // کلاس برای روز دیگر
  }
];